---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmorders.fulfillment.cloudkit.io
  labels:
    app.kubernetes.io/name: cloudkit
    app.kubernetes.io/component: fulfillment
    app.kubernetes.io/part-of: cloudkit-platform
spec:
  group: fulfillment.cloudkit.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
            - templateID
            - templateParameters
            properties:
              templateID:
                type: string
                description: "The ID of the VM template to use (e.g., ocp_virt_vm)"
                pattern: '^[a-zA-Z][a-zA-Z0-9_.-]*$'
              templateParameters:
                type: string
                description: "JSON string containing template-specific parameters"
              nodeRequests:
                type: array
                description: "Node resource requests (typically empty for VMs)"
                items:
                  type: object
                  properties:
                    numberOfNodes:
                      type: integer
                      minimum: 0
                    resourceClass:
                      type: string
                default: []
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - Pending
                - Provisioning
                - Ready
                - Failed
                - Deleting
                description: "Current phase of the VM order"
              message:
                type: string
                description: "Human readable message about the current status"
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              vmName:
                type: string
                description: "Name of the created VirtualMachine resource"
              vmNamespace:
                type: string
                description: "Namespace where the VM was created"
              createdResources:
                type: array
                description: "List of Kubernetes resources created for this VM"
                items:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
              credentials:
                type: object
                description: "Generated credentials for VM access"
                properties:
                  rootPassword:
                    type: string
                    description: "Generated root password (if applicable)"
                  sshKey:
                    type: string
                    description: "SSH public key for access"
    additionalPrinterColumns:
    - name: Template
      type: string
      description: "VM template ID"
      jsonPath: .spec.templateID
    - name: Phase
      type: string
      description: "Current phase"
      jsonPath: .status.phase
    - name: VM Name
      type: string
      description: "Created VM name"
      jsonPath: .status.vmName
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: vmorders
    singular: vmorder
    kind: VMOrder
    shortNames:
    - vmo
    - vmorder
    categories:
    - cloudkit
    - fulfillment